/**
 * English translations for the Happy app
 * Values can be:
 * - String constants for static text
 * - Functions with typed object parameters for dynamic text
 */

/**
 * English plural helper function
 * @param options - Object containing count, singular, and plural forms
 * @returns The appropriate form based on count
 */
function plural({ count, singular, plural }: { count: number; singular: string; plural: string }): string {
    return count === 1 ? singular : plural;
}

export const en = {
    tabs: {
        // Tab navigation labels
        sessions: 'Terminals',
        settings: 'Settings',
    },

    common: {
        // Simple string constants
        cancel: 'Cancel',
        authenticate: 'Authenticate',
        save: 'Save',
        saveAs: 'Save As',
        error: 'Error',
        success: 'Success',
        ok: 'OK',
        continue: 'Continue',
        back: 'Back',
        create: 'Create',
        rename: 'Rename',
        reset: 'Reset',
        logout: 'Logout',
        yes: 'Yes',
        no: 'No',
        discard: 'Discard',
        version: 'Version',
        copied: 'Copied',
        copy: 'Copy',
        scanning: 'Scanning...',
        urlPlaceholder: 'https://example.com',
        home: 'Home',
        message: 'Message',
        files: 'Files',
        fileViewer: 'File Viewer',
        loading: 'Loading...',
        retry: 'Retry',
        delete: 'Delete',
        archive: 'Archive',
        optional: 'optional',
    },

    pendingSwitch: {
        banner: 'Will switch to remote when current task ends',
    },

    requestSwitch: {
        now: 'Take over now',
        whenIdle: 'Send when idle',
    },

    cancelPendingSwitch: {
        label: 'Cancel switch',
        note: 'Message will be discarded',
    },

    abortPrompt: {
        title: 'Switch to remote control?',
        message: 'Claude is running locally. Choose how to hand off:',
        switchWhenIdle: 'Switch when idle',
        switchNow: 'Switch now (cancel turn)',
        cancel: 'Keep working locally',
    },

    commands: {
        rename: {
            emptyName: 'Add a chat name after /rename.',
            failure: 'Could not rename this chat. Please try again.',
        },
    },

    chat: {
        commandOutput: {
            stderrLabel: 'stderr',
        },
        boundaryDivider: {
            kind: {
                clear: 'Context cleared',
                compact: 'Compacted',
                autocompact: 'Auto-compacted',
                planModeEnter: 'Plan mode entered',
                planModeExit: 'Plan mode exited',
                sessionForkResume: 'Resumed from previous session',
            },
            crossDeviceAdvisory: 'Context cleared since you started — review?',
            showPreClearHistory: 'Show pre-clear history',
        },
        taskNotification: {
            title: 'Task notification',
            taskId: 'Task ID',
            toolUseId: 'Tool Use ID',
            taskType: 'Task Type',
            outputFile: 'Output File',
            summary: 'Summary',
            status: {
                completed: 'Completed',
                failed: 'Failed',
                killed: 'Stopped',
                running: 'Running',
                pending: 'Pending',
                unknown: 'Unknown',
            },
        },
    },

    profile: {
        userProfile: 'User Profile',
        details: 'Details',
        firstName: 'First Name',
        lastName: 'Last Name',
        username: 'Username',
        status: 'Status',
    },

    status: {
        connected: 'connected',
        connecting: 'connecting',
        disconnected: 'disconnected',
        error: 'error',
        online: 'online',
        offline: 'offline',
        lastSeen: ({ time }: { time: string }) => `last seen ${time}`,
        permissionRequired: 'permission required',
        activeNow: 'Active now',
        unknown: 'unknown',
        unread: 'new results',
    },

    time: {
        justNow: 'just now',
        minutesAgo: ({ count }: { count: number }) => `${count} minute${count !== 1 ? 's' : ''} ago`,
        hoursAgo: ({ count }: { count: number }) => `${count} hour${count !== 1 ? 's' : ''} ago`,
        daysAgo: ({ count }: { count: number }) => `${count} day${count !== 1 ? 's' : ''} ago`,
    },

    connect: {
        invalidSecretKey: 'Invalid secret key. Please check and try again.',
        enterUrlManually: 'Enter URL manually',
    },

    settings: {
        connectedServices: 'Connected Services',
        connectedServicesSubtitle: 'Optional GitHub connection',
        title: 'Settings',
        connectedAccounts: 'Connected Accounts',
        connectAccount: 'Connect account',
        github: 'GitHub',
        machines: 'Machines',
        showOfflineMachines: ({ count }: { count: number }) => count === 1 ? 'Show 1 offline machine' : `Show ${count} offline machines`,
        hideOfflineMachines: 'Hide offline machines',
        features: 'Features',
        social: 'Social',
        account: 'Account',
        accountSubtitle: 'Manage your account details',
        appearance: 'Appearance',
        appearanceSubtitle: 'Customize how the app looks',
        featuresTitle: 'Features',
        featuresSubtitle: 'Enable or disable app features',
        developer: 'Developer',
        developerTools: 'Developer Tools',
        about: 'About',
        aboutFooter: 'Happy Coder is a Codex and Claude Code mobile client that connects to your paired machines. Not affiliated with Anthropic.',
        whatsNew: 'What\'s New',
        whatsNewSubtitle: 'See the latest updates and improvements',
        reportIssue: 'Report an Issue',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        eula: 'EULA',
        supportUs: 'Support us',
        supportUsSubtitlePro: 'Thank you for your support!',
        supportUsSubtitle: 'Support project development',
        githubConnected: ({ login }: { login: string }) => `Connected as @${login}`,
        connectGithubAccount: 'Connect your GitHub account',
        claudeAuthSuccess: 'Successfully connected to Claude',
        exchangingTokens: 'Exchanging tokens...',
        // Dynamic settings messages
        accountConnected: ({ service }: { service: string }) => `${service} account connected`,
        machineStatus: ({ name, status }: { name: string; status: 'online' | 'offline' }) =>
            `${name} is ${status}`,
        featureToggled: ({ feature, enabled }: { feature: string; enabled: boolean }) =>
            `${feature} ${enabled ? 'enabled' : 'disabled'}`,
    },

    settingsAppearance: {
        // Appearance settings screen
        theme: 'Theme',
        themeDescription: 'Choose your preferred color scheme',
        themeOptions: {
            adaptive: 'Adaptive',
            light: 'Light', 
            dark: 'Dark',
        },
        themeDescriptions: {
            adaptive: 'Match system settings',
            light: 'Always use light theme',
            dark: 'Always use dark theme',
        },
        display: 'Display',
        displayDescription: 'Control layout and spacing',
        chatTextSizeTitle: 'Chat Text Size',
        chatTextSizePreview: 'Preview how chat messages will look at this size.',
        chatTextSizeFooter: 'Drag to preview chat text size. The new scale is saved when you release the slider.',
        pinchToZoomTitle: 'Pinch to Zoom Chat',
        pinchToZoomDescription: 'Use a two-finger pinch in chat for a live text-size preview that saves on release.',
        paginatedScrollTitle: 'Page-Turn Chat Navigation',
        paginatedScrollDescription: 'Use narrow top and bottom tap zones in chat to move by page instead of scrolling freely.',
        chatToolGroupingTitle: 'Group Tool Calls',
        chatToolGroupingDescription: 'Collapse tool calls and agent work into expandable groups (upstream style). Off by default — the flat e-ink layout renders every message inline.',
        messageCommandChipsTitle: 'Command & Goal Chips',
        messageCommandChipsDescription: 'Restore upstream slash-command and goal chips plus long-press to fork from a message. Off by default — the fork renders user messages as a flat e-ink band.',
        socketRangeFetchTitle: 'Stream Older Messages',
        socketRangeFetchDescription: 'Fetch older messages over the live socket instead of one-off HTTP requests, so they arrive a bit before you scroll there.',
        inlineToolCalls: 'Inline Tool Calls',
        inlineToolCallsDescription: 'Display tool calls directly in chat messages',
        expandTodoLists: 'Expand Todo Lists',
        expandTodoListsDescription: 'Show all todos instead of just changes',
        showLineNumbersInDiffs: 'Show Line Numbers in Diffs',
        showLineNumbersInDiffsDescription: 'Display line numbers in code diffs',
        showLineNumbersInToolViews: 'Show Line Numbers in Tool Views',
        showLineNumbersInToolViewsDescription: 'Display line numbers in tool view diffs',
        wrapLinesInDiffs: 'Wrap Lines in Diffs',
        wrapLinesInDiffsDescription: 'Wrap long lines instead of horizontal scrolling in diff views',
        diffStyle: 'Diff View',
        diffStyleDescription: 'Show diffs as a single column (unified) or side-by-side (split). Split view is web-only.',
        diffStyleOptions: {
            unified: 'Unified',
            split: 'Split',
        },
        alwaysShowContextSize: 'Always Show Context Size',
        alwaysShowContextSizeDescription: 'Display context usage even when not near limit',
        avatarStyle: 'Avatar Style',
        avatarStyleDescription: 'Choose session avatar appearance',
        avatarOptions: {
            pixelated: 'Pixelated',
            gradient: 'Gradient',
            brutalist: 'Brutalist',
            brutalistTopic: 'Topic-aware Brutalist',
        },
        showFlavorIcons: 'Show AI Provider Icons',
        showFlavorIconsDescription: 'Display AI provider icons on session avatars',
    },

    settingsFeatures: {
        // Features settings screen
        experiments: 'Experiments',
        experimentsDescription: 'Enable experimental features that are still in development. These features may be unstable or change without notice.',
        experimentalFeatures: 'Experimental Features',
        experimentalFeaturesEnabled: 'Experimental features enabled',
        experimentalFeaturesDisabled: 'Using stable features only',
        webFeatures: 'Web Features',
        webFeaturesDescription: 'Features available only in the web version of the app.',
        enterToSend: 'Enter to Send',
        enterToSendEnabled: 'Press Enter to send (Shift+Enter for a new line)',
        enterToSendDisabled: 'Enter inserts a new line',
        commandPalette: 'Command Palette',
        commandPaletteEnabled: 'Press ⌘K to open',
        commandPaletteDisabled: 'Quick command access disabled',
        markdownCopyV2: 'Markdown Copy v2',
        markdownCopyV2Subtitle: 'Long press opens copy modal',
        unifiedNewSessionComposer: 'Unified New Session Composer',
        unifiedNewSessionComposerSubtitle: 'Use the shared composer on the new-session screen',
        hideInactiveSessions: 'Hide inactive sessions',
        hideInactiveSessionsSubtitle: 'Show only active chats in your list',
        groupToolCalls: 'Group Tool Calls',
        groupToolCallsSubtitle: 'Collapse consecutive tool calls into one container',
        privacy: 'Privacy',
        privacyDescription: 'Completely disables all analytics and telemetry. No data will be sent to PostHog or any other tracking service.',
        disableAnalytics: 'Disable Analytics',
        analyticsDisabled: 'All tracking and telemetry disabled',
        analyticsEnabled: 'Anonymous usage analytics active',
        imageUpload: 'Image Upload',
        imageUploadSubtitle: 'Attach images to messages for supported agents to analyze',
    },

    imageUpload: {
        permissionTitle: 'Photo Library Access',
        permissionMessage: 'Allow access to your photo library to attach images to messages.',
        limitTitle: 'Image Limit Reached',
        limitMessage: ({ max }: { max: number }) => `You can attach up to ${max} images per message.`,
        fileTooLargeTitle: 'File Too Large',
        fileTooLargeMessage: ({ name, maxMb }: { name: string; maxMb: number }) => `"${name}" exceeds the ${maxMb}MB limit and was not added.`,
        uploadFailedTitle: 'Upload Failed',
        uploadFailedMessage: ({ count }: { count: number }) => count === 1
            ? 'One image could not be uploaded and was not sent.'
            : `${count} images could not be uploaded and were not sent.`,
        notSupportedTitle: 'Images Not Supported',
        notSupportedMessage: 'This agent does not support image attachments. Images were not sent.',
    },

    errors: {
        networkError: 'Network error occurred',
        serverError: 'Server error occurred',
        unknownError: 'An unknown error occurred',
        connectionTimeout: 'Connection timed out',
        authenticationFailed: 'Authentication failed',
        permissionDenied: 'Permission denied',
        fileNotFound: 'File not found',
        invalidFormat: 'Invalid format',
        operationFailed: 'Operation failed',
        tryAgain: 'Please try again',
        contactSupport: 'Contact support if the problem persists',
        sessionNotFound: 'Session not found',
        oauthInitializationFailed: 'Failed to initialize OAuth flow',
        tokenStorageFailed: 'Failed to store authentication tokens',
        oauthStateMismatch: 'Security validation failed. Please try again',
        tokenExchangeFailed: 'Failed to exchange authorization code',
        oauthAuthorizationDenied: 'Authorization was denied',
        webViewLoadFailed: 'Failed to load authentication page',
        failedToLoadProfile: 'Failed to load user profile',
        userNotFound: 'User not found',
        sessionDeleted: 'Session has been deleted',
        sessionDeletedDescription: 'This session has been permanently removed',
        requestSwitchFailed: 'Failed to update switch request',
        sendFailed: 'Failed to send message',
        attachmentPerFileTooLarge: 'Each attachment must be 25 MB or smaller',
        attachmentTotalTooLarge: 'Attachments must total 100 MB or less',
        attachmentUploadFailed: 'Could not attach file. Please try again.',
        attachmentTooLarge: 'Image attachments must be 4 MB or smaller',
        attachmentUnsupportedType: 'Only JPEG and PNG images can be attached',
        attachmentPickFailed: 'Failed to attach image',

        // Error functions with context
        fieldError: ({ field, reason }: { field: string; reason: string }) =>
            `${field}: ${reason}`,
        validationError: ({ field, min, max }: { field: string; min: number; max: number }) =>
            `${field} must be between ${min} and ${max}`,
        retryIn: ({ seconds }: { seconds: number }) =>
            `Retry in ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
        errorWithCode: ({ message, code }: { message: string; code: number | string }) =>
            `${message} (Error ${code})`,
        searchFailed: 'Search failed. Please try again.',
        deviceCodeExpiredTitle: 'Machine pairing expired',
        deviceCodeExpiredMessage: ({ machineId }: { machineId: string }) =>
            `The pairing for machine "${machineId}" has expired. Please re-pair this machine to restore the connection.`,
    },

    newSession: {
        title: 'Start New Session',
        selectMachineRequired: 'Please select a machine',
        machineOffline: 'Machine is offline',
        switchMachinesHint: '• Switch machines by clicking on the machine above',
        imageAttachment: 'Image attachment',
    },

    sessionHistory: {
        // Used by session history screen
        title: 'Session History',
        empty: 'No sessions found',
        today: 'Today',
        yesterday: 'Yesterday',
        daysAgo: ({ count }: { count: number }) => `${count} ${count === 1 ? 'day' : 'days'} ago`,
        viewAll: 'View all sessions',
    },

    session: {
        inputPlaceholder: 'Type a message ...',
        inactiveArchived: 'This session is inactive.',
        resumeFromTerminal: 'To resume it from the terminal:',
        catalogNotReadyBanner: "Session hasn't loaded yet — send any message first to populate this list.",
        newChat: 'New chat',
        // Fork / duplicate / rewind flow (Claude only)
        forkAction: 'Fork session',
        forkSubtitle: 'Continue in a new session with the same context',
        duplicateAction: 'Duplicate from message…',
        duplicateSubtitle: 'Rewind to a chosen point and try again',
        forkFromHere: 'Fork from here',
        duplicateSheetTitle: 'Choose a rewind point',
        duplicateSheetSubtitle: 'The new session keeps the chosen turn complete (your message and the agent’s response) and drops every prompt after it.',
        duplicateSheetConfirm: 'Duplicate',
        duplicateSheetEmpty: 'No messages eligible for rewind in this session yet.',
        duplicateRowDisabled: "This message can't be used as a rewind point.",
        forkedFromLabel: 'Forked from',
        forkedFromSubtitle: 'Open the session this fork was branched from',
        forkErrorOffline: 'This machine is offline. Fork is only available while the machine that owns the session is online.',
        forkErrorMissingUuid: 'The chosen rewind point is no longer present in the source session — try forking without truncation.',
        forkErrorMissingMetadata: 'Missing session metadata required to fork.',
        forkErrorGeneric: 'Failed to fork the session.',
        forkClaudeOnly: 'Fork is currently only supported for Claude sessions.',
    },

    commandPalette: {
        placeholder: 'Type a command or search...',
    },

    pickers: {
        noResults: 'No results',
    },

    drawer: {
        fork: {
            action: 'Fork',
            comingSoon: 'Coming soon',
        },
        spawnChild: {
            action: 'Spawn child',
        },
        pinIcon: 'Pin icon',
        pinIconDescription: 'Keep this session icon even if the topic changes',
        unpinIcon: 'Unpin icon',
        applyFailed: 'Failed to apply — please try again',
    },

    forkComposer: {
        title: 'Fork session',
        parentLabel: ({ name }: { name: string }) => `Forking from ${name}`,
        submit: 'Fork',
        creatingWorktree: 'Creating worktree...',
        createNew: 'Create new',
        currentCheckout: 'Current checkout',
        worktree: 'Worktree',
        machine: 'Machine',
        agent: 'Agent',
        codex: 'Codex',
        defaultModel: 'default model',
        defaultPermission: 'default',
        defaultEffort: 'default',
        searchWorktrees: 'search worktrees...',
        searchModels: 'search models...',
        searchPermissions: 'search permissions...',
        searchEffort: 'search effort levels...',
        errors: {
            parentMissing: 'Parent session is missing',
            worktreeMissing: ({ directory }: { directory: string }) => `Worktree path is unavailable: ${directory}`,
            flavorUnsupported: 'Only Codex sessions can be forked',
            forkFailed: 'Failed to fork session',
            createWorktreeFailed: 'Failed to create worktree',
        },
    },

    spawnChild: {
        title: 'Spawn child agent',
        parentLabel: ({ name }: { name: string }) => `Spawning from ${name}`,
        submit: 'Spawn child',
        spawning: 'Spawning child...',
        machine: 'Machine',
        project: 'Project',
        agent: 'Agent',
        defaultModel: 'default model',
        defaultPermission: 'default',
        defaultEffort: 'default',
        initialMessage: 'Initial message',
        initialMessagePlaceholder: 'Optional message to send after the child starts',
        searchAgents: 'search agents...',
        searchModels: 'search models...',
        searchPermissions: 'search permissions...',
        searchEffort: 'search effort levels...',
        agents: {
            claude: 'Claude Code',
            codex: 'Codex',
            openclaw: 'OpenClaw',
            gemini: 'Gemini',
        },
        errors: {
            parentMissing: 'Parent session is missing',
            spawnFailed: 'Failed to spawn child session',
        },
    },

    connections: {
        title: 'Connected Services',
        githubTitle: 'GitHub',
        githubDescription: 'Connect your GitHub account to show your profile in Happy. This is optional and separate from pairing.',
        connect: 'Connect GitHub',
        connecting: 'Connecting...',
        disconnecting: 'Disconnecting...',
        disconnect: 'Disconnect',
        disconnectConfirmTitle: 'Disconnect GitHub?',
        disconnectConfirmMessage: 'Your GitHub profile will be removed from Happy. You can reconnect at any time.',
        connectedAs: ({ login }: { login: string }) => `Connected as @${login}`,
        unavailable: 'GitHub connection is not configured on this server.',
        error: 'Something went wrong. Please try again.',
    },
    server: {
        publicPairing: {
            confirmTitle: 'Confirm pairing',
            confirmLocal: ({ host }: { host: string }) => `Pair with local server ${host}?`,
            confirmPublic: ({ host }: { host: string }) => `Pair with public server ${host}?`,
            expiresInSeconds: ({ seconds }: { seconds: number }) => `Invite expires in ${seconds}s`,
            expired: 'This pairing invite has expired. Ask for a fresh invite.',
            unsupportedPlatform: 'Local pairing invites can only be used from the web app.',
            networkError: 'Could not reach the server. Check the address and try again.',
            denied: 'The server rejected this pairing attempt.',
            identityChangedTitle: 'Server identity changed',
            identityChangedMessage: 'This machine already trusts a different server key. Pairing was blocked to protect you. Remove the saved machine and pair again only if you trust this server.',
            removeAndRepair: 'Remove & pair again',
            identityRepaired: 'Saved machine removed. Paste a fresh invite to pair this device again.',
            confirmButton: 'Pair',
            success: 'Machine paired',
            sectionTitle: 'Pair with a Server',
            sectionFooter: 'Paste a pairing invite from the Happy server you want to connect to. Local and public invites are validated separately.',
            invitePlaceholder: 'Paste pairing invite',
            pairButton: 'Pair with server',
            invalidInvite: 'That pairing invite is invalid or has expired.',
            failed: 'Pairing failed. Check the invite and try again.',
        },

        // Used by Server Configuration screen (app/(app)/server.tsx)
        serverConfiguration: 'Server Configuration',
        enterServerUrl: 'Please enter a server URL',
        notValidHappyServer: 'Not a valid Happy Server',
        changeServer: 'Change Server',
        continueWithServer: 'Continue with this server?',
        resetToDefault: 'Reset to Default',
        resetServerDefault: 'Reset server to default?',
        validating: 'Validating...',
        validatingServer: 'Validating server...',
        serverReturnedError: 'Server returned an error',
        failedToConnectToServer: 'Failed to connect to server',
        currentlyUsingCustomServer: 'Currently using custom server',
        customServerUrlLabel: 'Custom Server URL',
        advancedFeatureFooter: "This is an advanced feature. Only change the server if you know what you're doing. You will need to log out and log in again after changing servers."
    },

    sessionInfo: {
        // Used by Session Info screen (app/(app)/session/[id]/info.tsx)
        killSession: 'Kill Session',
        killSessionConfirm: 'Are you sure you want to terminate this session?',
        archiveSession: 'Archive Session',
        archiveSessionConfirm: 'Archive this session? Archived sessions can be resumed at any time.',
        happySessionIdCopied: 'Happy Session ID copied to clipboard',
        failedToCopySessionId: 'Failed to copy Happy Session ID',
        happySessionId: 'Happy Session ID',
        claudeCodeSessionId: 'Claude Code Session ID',
        claudeCodeSessionIdCopied: 'Claude Code Session ID copied to clipboard',
        codexThreadId: 'Codex Thread ID',
        codexThreadIdCopied: 'Codex Thread ID copied to clipboard',
        aiProvider: 'AI Provider',
        failedToCopyClaudeCodeSessionId: 'Failed to copy Claude Code Session ID',
        failedToCopyCodexThreadId: 'Failed to copy Codex Thread ID',
        metadataCopied: 'Session metadata copied to clipboard',
        failedToCopyMetadata: 'Failed to copy session metadata',
        failedToKillSession: 'Failed to kill session',
        failedToArchiveSession: 'Failed to archive session',
        connectionStatus: 'Connection Status',
        created: 'Created',
        lastUpdated: 'Last Updated',
        sequence: 'Sequence',
        quickActions: 'Quick Actions',
        viewMachine: 'View Machine',
        viewMachineSubtitle: 'View machine details and sessions',
        resumeSession: 'Resume Session',
        resumeSessionSubtitle: 'Resume this session on the same machine',
        resumeSessionSameMachineOnly: 'This session can only be resumed on the same machine it started on.',
        resumeSessionMachineOffline: 'This machine is offline. Resume is only available while it is online.',
        resumeSessionNeedsHappyAgent: 'Resume is unavailable on this machine. Run `happy-agent auth login` to enable it.',
        resumeSessionMissingMachine: 'This session is missing its machine metadata, so it cannot be resumed.',
        resumeSessionMissingBackendId: 'This session does not have a resumable Claude or Codex identifier.',
        resumeSessionUnexpectedDirectoryPrompt: 'Resume cannot create directories. Start the session manually from its original path.',
        killSessionSubtitle: 'Immediately terminate the session',
        archiveSessionSubtitle: 'Archive this session and stop it',
        metadata: 'Metadata',
        host: 'Host',
        path: 'Path',
        operatingSystem: 'Operating System',
        processId: 'Process ID',
        happyHome: 'Happy Home',
        copyMetadata: 'Copy session metadata',
        agentState: 'Agent State',
        controlledByUser: 'Controlled by User',
        pendingRequests: 'Pending Requests',
        activity: 'Activity',
        thinking: 'Thinking',
        thinkingSince: 'Thinking Since',
        cliVersion: 'CLI Version',
        cliVersionOutdated: 'CLI Update Required',
        cliVersionOutdatedMessage: ({ currentVersion, requiredVersion }: { currentVersion: string; requiredVersion: string }) =>
            `Version ${currentVersion} installed. Update to ${requiredVersion} or later`,
        updateCliInstructions: 'Please run npm install -g happy@latest',
        deleteSession: 'Delete Session',
        deleteSessionSubtitle: 'Permanently remove this session',
        deleteSessionConfirm: 'Delete Session Permanently?',
        deleteSessionWarning: 'This action cannot be undone. All messages and data associated with this session will be permanently deleted.',
        failedToDeleteSession: 'Failed to delete session',
        sessionDeleted: 'Session deleted successfully',
        worktreeCleanupTitle: 'Delete Worktree?',
        worktreeCleanupMessage: 'The worktree has no uncommitted changes. Would you like to delete the worktree files?',
        worktreeCleanupDelete: 'Delete Worktree',
        worktreeCleanupKeep: 'Keep Files',
        plugins: 'Plugins',
        pluginsSubtitle: 'View plugins loaded in this session',
        skills: 'Skills',
        skillsSubtitle: 'View skills loaded in this session',
        agents: 'Agents',
        agentsSubtitle: 'View available subagents for this session',
    },

    components: {
        emptyMainScreen: {
            // Used by EmptyMainScreen component
            readyToCode: 'Ready to code?',
            installCli: 'Install the Happy CLI',
            runIt: 'Run it',
            scanQrCode: 'Scan the QR code',
            openCamera: 'Open Camera',
        },
        agentGoalBar: {
            currentGoal: 'Current goal',
            accessibilityLabel: ({ goal }: { goal: string }) => `Current goal: ${goal}`,
            clearGoal: 'Clear goal',
            stopGoal: 'Stop goal',
            editGoal: 'Edit goal',
        },
    },

    agentInput: {
        permissionMode: {
            title: 'PERMISSION MODE',
            default: 'default permissions',
            acceptEdits: 'accept edits',
            plan: 'plan',
            dontAsk: "don't ask",
            bypassPermissions: 'yolo',
            badgeAcceptAllEdits: 'accept all edits',
            badgeBypassAllPermissions: 'yolo',
            badgePlanMode: 'plan mode',
        },
        textSize: {
            title: 'TEXT SIZE',
        },
        chatWidth: {
            title: 'Chat Width',
        },
        agent: {
            claude: 'Claude',
            codex: 'Codex',
            gemini: 'Gemini',
            openclaw: 'OpenClaw',
        },
        model: {
            title: 'MODEL',
            configureInCli: 'Configure models in CLI settings',
        },
        effort: {
            title: 'EFFORT',
        },
        codexPermissionMode: {
            title: 'CODEX PERMISSION MODE',
            default: 'default permissions',
            readOnly: 'read-only',
            safeYolo: 'safe yolo',
            yolo: 'yolo',
            badgeReadOnly: 'read-only',
            badgeSafeYolo: 'safe yolo',
            badgeYolo: 'yolo',
        },
        codexModel: {
            title: 'CODEX MODEL',
            gpt5CodexLow: 'gpt-5-codex low',
            gpt5CodexMedium: 'gpt-5-codex medium',
            gpt5CodexHigh: 'gpt-5-codex high',
            gpt5Minimal: 'GPT-5 Minimal',
            gpt5Low: 'GPT-5 Low',
            gpt5Medium: 'GPT-5 Medium',
            gpt5High: 'GPT-5 High',
        },
        geminiPermissionMode: {
            title: 'GEMINI PERMISSION MODE',
            default: 'default permissions',
            autoEdit: 'auto edit',
            yolo: 'yolo',
            plan: 'plan',
            badgeAutoEdit: 'auto edit',
            badgeYolo: 'yolo',
            badgePlan: 'plan',
        },
        context: {
            remaining: ({ percent }: { percent: number }) => `${percent}% left`,
        },
        suggestion: {
            fileLabel: 'FILE',
            folderLabel: 'FOLDER',
        },
        attachments: {
            attachButton: 'Attach file',
            dropIdle: 'Drop files here',
            dropActive: 'Release to attach',
            pasteHint: 'Paste files to attach',
            removeButton: ({ name }: { name: string }) => `Remove ${name}`,
        },
        noMachinesAvailable: 'No machines',
    },

    machineLauncher: {
        showLess: 'Show less',
        showAll: ({ count }: { count: number }) => `Show all (${count} paths)`,
        enterCustomPath: 'Enter custom path',
        offlineUnableToSpawn: 'Unable to spawn new session, offline',
    },

    sidebar: {
        sessionsTitle: 'Happy',
        showArchived: 'Show archived',
        hideArchived: 'Hide archived',
        show: 'Show sidebar',
        hide: 'Hide sidebar',
        hideHint: 'Enters max-focus mode; a menu button restores the sidebar',
        expand: 'Expand sidebar',
        collapse: 'Collapse sidebar',
        newSession: 'New session',
    },

    zen: {
        toggle: 'Zen mode',
    },

    toolView: {
        input: 'Input',
        output: 'Output',
    },

    toolGroup: {
        editedFile: 'Edited file',
        editedFiles: ({ count }: { count: number }) => count === 1 ? 'Edited 1 file' : `Edited ${count} files`,
        readFiles: ({ count }: { count: number }) => count === 1 ? 'Read 1 file' : `Read ${count} files`,
        ranCommands: ({ count }: { count: number }) => count === 1 ? 'Ran 1 command' : `Ran ${count} commands`,
        searched: ({ count }: { count: number }) => count === 1 ? 'Searched 1 time' : `Searched ${count} times`,
        fetchedUrls: ({ count }: { count: number }) => count === 1 ? 'Fetched 1 URL' : `Fetched ${count} URLs`,
        ranTasks: ({ count }: { count: number }) => count === 1 ? 'Ran 1 task' : `Ran ${count} tasks`,
        usedTools: ({ count }: { count: number }) => count === 1 ? 'Used 1 tool' : `Used ${count} tools`,
        workedFor: ({ duration }: { duration: string }) => `Worked ${duration}`,
    },
    tools: {
        fullView: {
            description: 'Description',
            inputParams: 'Input Parameters',
            output: 'Output',
            error: 'Error',
            completed: 'Tool completed successfully',
            noOutput: 'No output was produced',
            running: 'Tool is running...',
            rawJsonDevMode: 'Raw JSON (Dev Mode)',
        },
        taskView: {
            initializing: 'Initializing agent...',
            moreTools: ({ count }: { count: number }) => `+${count} more ${plural({ count, singular: 'tool', plural: 'tools' })}`,
            moreSteps: ({ count }: { count: number }) => `+${count} more ${plural({ count, singular: 'step', plural: 'steps' })}`,
        },
        taskOutput: {
            taskId: ({ taskId }: { taskId: string }) => `Task ${taskId}`,
            blocking: 'Blocking',
            timeout: ({ timeout }: { timeout: number }) => `Timeout: ${timeout}ms`,
            parseError: 'Task output result could not be parsed',
            running: 'Waiting for task output...',
            truncated: 'Output truncated',
        },
        taskStop: {
            taskId: ({ taskId }: { taskId: string }) => `Task ${taskId}`,
            parseError: 'Task stop result could not be parsed',
            running: 'Stopping task...',
            stopped: 'Stopped',
            notFound: 'Not found',
            alreadyStopped: 'Already stopped',
        },
        edit: {
            parseError: 'Edit input could not be parsed',
        },
        multiEdit: {
            editNumber: ({ index, total }: { index: number; total: number }) => `Edit ${index} of ${total}`,
            replaceAll: 'Replace All',
            parseError: 'MultiEdit input could not be parsed',
        },
        diff: {
            showMore: ({ count }: { count: number }) => count === 1 ? 'Show 1 more line' : `Show ${count} more lines`,
            collapse: 'Collapse',
        },
        names: {
            task: 'Task',
            agent: 'Agent',
            taskOutput: 'Task output',
            taskOutputWithId: ({ taskId }: { taskId: string }) => `Task Output · ${taskId}`,
            taskStop: 'Stop task',
            taskStopWithId: ({ taskId }: { taskId: string }) => `Stop Task · ${taskId}`,
            taskList: 'List tasks',
            taskGet: 'Get task',
            taskUpdate: 'Update task',
            terminal: 'Terminal',
            searchFiles: 'Search Files',
            search: 'Search',
            searchContent: 'Search Content',
            listFiles: 'List Files',
            planProposal: 'Plan proposal',
            readFile: 'Read File',
            editFile: 'Edit File',
            writeFile: 'Write File',
            fetchUrl: 'Fetch URL',
            readNotebook: 'Read Notebook',
            editNotebook: 'Edit Notebook',
            todoList: 'Todo List',
            webSearch: 'Web Search',
            reasoning: 'Reasoning',
            applyChanges: 'Update file',
            viewDiff: 'Current file changes',
            question: 'Question',
        },
        askUserQuestion: {
            submit: 'Submit Answer',
            multipleQuestions: ({ count }: { count: number }) => `${count} questions`,
            other: 'Other',
            otherDescription: 'Type your own answer',
            otherPlaceholder: 'Type your answer...',
        },
        desc: {
            terminalCmd: ({ cmd }: { cmd: string }) => `Terminal(cmd: ${cmd})`,
            searchPattern: ({ pattern }: { pattern: string }) => `Search(pattern: ${pattern})`,
            searchPath: ({ basename }: { basename: string }) => `Search(path: ${basename})`,
            fetchUrlHost: ({ host }: { host: string }) => `Fetch URL(url: ${host})`,
            editNotebookMode: ({ path, mode }: { path: string; mode: string }) => `Edit Notebook(file: ${path}, mode: ${mode})`,
            todoListCount: ({ count }: { count: number }) => `Todo List(count: ${count})`,
            webSearchQuery: ({ query }: { query: string }) => `Web Search(query: ${query})`,
            grepPattern: ({ pattern }: { pattern: string }) => `grep(pattern: ${pattern})`,
            multiEditEdits: ({ path, count }: { path: string; count: number }) => `${path} (${count} edits)`,
            readingFile: ({ file }: { file: string }) => `Reading ${file}`,
            writingFile: ({ file }: { file: string }) => `Writing ${file}`,
            modifyingFile: ({ file }: { file: string }) => `Modifying ${file}`,
            modifyingFiles: ({ count }: { count: number }) => `Modifying ${count} files`,
            modifyingMultipleFiles: ({ file, count }: { file: string; count: number }) => `${file} and ${count} more`,
            showingDiff: 'Showing changes',
        }
    },

    files: {
        changes: 'Changes',
        refreshChanges: 'Refresh changes',
        refreshChangesHint: 'Fetch the latest changed files',
        searchPlaceholder: 'Search files...',
        detachedHead: 'detached HEAD',
        summary: ({ staged, unstaged }: { staged: number; unstaged: number }) => `${staged} staged • ${unstaged} unstaged`,
        notRepo: 'Not a git repository',
        notUnderGit: 'This directory is not under git version control',
        searching: 'Searching files...',
        noFilesFound: 'No files found',
        noFilesInProject: 'No files in project',
        tryDifferentTerm: 'Try a different search term',
        searchResults: ({ count }: { count: number }) => `Search Results (${count})`,
        projectRoot: 'Project root',
        stagedChanges: ({ count }: { count: number }) => `Staged Changes (${count})`,
        unstagedChanges: ({ count }: { count: number }) => `Unstaged Changes (${count})`,
        // File viewer strings
        loadingFile: ({ fileName }: { fileName: string }) => `Loading ${fileName}...`,
        binaryFile: 'Binary File',
        cannotDisplayBinary: 'Cannot display binary file content',
        diff: 'Diff',
        file: 'File',
        fileEmpty: 'File is empty',
        noChanges: 'No changes to display',
        noChangesTitle: 'No changes',
        noChangesSubtitle: 'Working tree is clean',
        deleted: 'Deleted',
        changedFiles: ({ count }: { count: number }) => `${count} changed ${count === 1 ? 'file' : 'files'}`,
        allFiles: 'All Files',
        editFile: 'Edit',
        saveFile: 'Save',
        failedToRead: 'Failed to read file',
        failedToSave: 'Failed to save file',
        fileConflict: 'File conflict',
        fileConflictDescription: 'This file was modified on the device while you were editing. Reload to see the latest version.',
        reload: 'Reload',
        overwrite: 'Overwrite',
    },

    settingsAccount: {
        // Account settings screen
        accountInformation: 'Account Information',
        status: 'Status',
        statusActive: 'Active',
        statusNotAuthenticated: 'Not Authenticated',
        anonymousId: 'Anonymous ID',
        publicId: 'Public ID',
        notAvailable: 'Not available',
        linkNewDevice: 'Link New Device',
        profile: 'Profile',
        name: 'Name',
        github: 'GitHub',
        tapToDisconnect: 'Tap to disconnect',
        server: 'Server',
        backup: 'Backup',
        tapToReveal: 'Tap to reveal',
        tapToHide: 'Tap to hide',
        privacy: 'Privacy',
        privacyDescription: 'Help improve the app by sharing anonymous usage data. No personal information is collected.',
        analytics: 'Analytics',
        analyticsDisabled: 'No data is shared',
        analyticsEnabled: 'Anonymous usage data is shared',
        dangerZone: 'Danger Zone',
        logout: 'Logout',
        logoutSubtitle: 'Sign out and clear local data',
        logoutConfirm: 'Are you sure you want to logout? Make sure you have backed up your secret key!',
    },

    settingsLanguage: {
        // Language settings screen
        title: 'Language',
        description: 'Choose your preferred language for the app interface. This will sync across all your devices.',
        currentLanguage: 'Current Language',
        automatic: 'Automatic',
        automaticSubtitle: 'Detect from device settings',
        needsRestart: 'Language Changed',
        needsRestartMessage: 'The app needs to restart to apply the new language setting.',
        restartNow: 'Restart Now',
    },


    updateBanner: {
        updateAvailable: 'Update available',
        pressToApply: 'Press to apply the update',
        whatsNew: "What's new",
        seeLatest: 'See the latest updates and improvements',
        nativeUpdateAvailable: 'App Update Available',
        tapToUpdateAppStore: 'Tap to update in App Store',
        tapToUpdatePlayStore: 'Tap to update in Play Store',
    },

    changelog: {
        // Used by the changelog screen
        version: ({ version }: { version: number }) => `Version ${version}`,
        noEntriesAvailable: 'No changelog entries available.',
    },


    modals: {
        // Used across connect flows and settings
        authenticateTerminal: 'Authenticate Terminal',
        pasteUrlFromTerminal: 'Paste the authentication URL from your terminal',
        deviceLinkedSuccessfully: 'Device linked successfully',
        terminalConnectedSuccessfully: 'Terminal connected successfully',
        invalidAuthUrl: 'Invalid authentication URL',
        developerMode: 'Developer Mode',
        developerModeEnabled: 'Developer mode enabled',
        developerModeDisabled: 'Developer mode disabled',
        disconnectGithub: 'Disconnect GitHub',
        disconnectGithubConfirm: 'Are you sure you want to disconnect your GitHub account?',
        disconnect: 'Disconnect',
        failedToConnectTerminal: 'Failed to connect terminal',
        cameraPermissionsRequiredToConnectTerminal: 'Camera permissions are required to connect terminal',
        failedToLinkDevice: 'Failed to link device',
        cameraPermissionsRequiredToScanQr: 'Camera permissions are required to scan QR codes'
    },

    navigation: {
        // Navigation titles and screen headers
        linkNewDevice: 'Link New Device', 
        whatsNew: "What's New",
    },

    welcome: {
        // Main welcome screen for unauthenticated users
        title: 'Codex and Claude Code mobile client',
        subtitle: 'Pair this device with your machine using a one-time invite.',
        createAccount: 'Create account',
        linkOrRestoreAccount: 'Link or restore account',
        loginWithMobileApp: 'Login with mobile app',
        pairMachine: 'Pair machine',
        noMachinesForIdentity: 'No machines returned for this GitHub identity',
        deviceAuthorizationExpired: 'GitHub device authorization expired',
        pairingFailed: 'Failed to pair machine',
        selectMachine: 'Select a machine',
        selectMachineSubtitle: ({ login }: { login: string }) => `Signed in as @${login}. Choose a machine to connect.`,
        thisServer: 'This server',
        connectTo: 'Connect',
        online: 'Online',
        offline: 'Offline',
    },

    review: {
        // Used by utils/requestReview.ts
        enjoyingApp: 'Enjoying the app?',
        feedbackPrompt: "We'd love to hear your feedback!",
        yesILoveIt: 'Yes, I love it!',
        notReally: 'Not really'
    },

    items: {
        // Used by Item component for copy toast
        copiedToClipboard: ({ label }: { label: string }) => `${label} copied to clipboard`
    },

    machine: {
        launchNewSessionInDirectory: 'Launch New Session in Directory',
        offlineUnableToSpawn: 'Launcher disabled while machine is offline',
        offlineHelp: '• Make sure your computer is online\n• Run `happy daemon status` to diagnose\n• Are you running the latest CLI version? Upgrade with `npm install -g happy@latest`',
        daemon: 'Daemon',
        status: 'Status',
        stopDaemon: 'Stop Daemon',
        lastKnownPid: 'Last Known PID',
        lastKnownHttpPort: 'Last Known HTTP Port',
        startedAt: 'Started At',
        cliVersion: 'CLI Version',
        daemonStateVersion: 'Daemon State Version',
        activeSessions: ({ count }: { count: number }) => `Active Sessions (${count})`,
        machineGroup: 'Machine',
        host: 'Host',
        machineId: 'Machine ID',
        username: 'Username',
        homeDirectory: 'Home Directory',
        platform: 'Platform',
        architecture: 'Architecture',
        lastSeen: 'Last Seen',
        never: 'Never',
        metadataVersion: 'Metadata Version',
        cliAvailability: 'CLI Availability',
        cliInstalled: 'Installed',
        cliNotFound: 'Not found',
        lastDetected: 'Last Detected',
        untitledSession: 'Untitled Session',
        back: 'Back',
        dangerZone: 'Danger Zone',
        delete: 'Delete Machine',
        deleteFooter: 'Remove this machine from your account. Session history will be preserved, but you will not be able to start new sessions on this machine.',
        deleteConfirmTitle: 'Delete this machine?',
        deleteConfirmMessage: 'The machine will be removed from your account. Session history will be preserved, but you will not be able to start new sessions until you reconnect the daemon.',
        deleteFailed: 'Failed to delete machine.',
    },

    message: {
        switchedToMode: ({ mode }: { mode: string }) => `Switched to ${mode} mode`,
        unknownEvent: 'Unknown event',
        sentAsGoal: 'Sent as goal',
        usageLimitUntil: ({ time }: { time: string }) => `Usage limit reached until ${time}`,
        unknownTime: 'unknown time',
    },

    codex: {
        // Codex permission dialog buttons
        permissions: {
            yesForSession: "Yes, and don't ask for a session",
            stopAndExplain: 'Stop, and explain what to do',
        }
    },

    claude: {
        // Claude permission dialog buttons
        permissions: {
            yesAllowAllEdits: 'Yes, allow all edits during this session',
            yesAllowEverything: 'Yes, allow everything during this session',
            yesForTool: "Yes, don't ask again for this tool",
            noTellClaude: 'No, and provide feedback',
        }
    },

    textSelection: {
        // Text selection screen
        selectText: 'Select text range',
        title: 'Select Text',
        noTextProvided: 'No text provided',
        textNotFound: 'Text not found or expired',
        textCopied: 'Text copied to clipboard',
        failedToCopy: 'Failed to copy text to clipboard',
        noTextToCopy: 'No text available to copy',
    },

    markdown: {
        // Markdown copy functionality
        codeCopied: 'Code copied',
        copyFailed: 'Copy failed',
        mermaidRenderFailed: 'Failed to render mermaid diagram',
    },

    copilotSteering: {
        // T6 Copilot steering panel — lease UX + prompt-answer composer.
        statusObserving: 'Observing (read-only)',
        requestSteering: 'Request steering',
        requesting: 'Requesting steering…',
        steeringActive: 'Steering active',
        steeringActiveUntil: ({ time }: { time: string }) => `Steering active · until ${time}`,
        release: 'Release steering',
        releasing: 'Releasing…',
        anotherClientSteering: 'Another client is currently steering',
        anotherClientRequesting: 'Another client is requesting steering',
        revokedKeystroke: 'The human took over at the terminal',
        revokedExpired: 'Your steering lease expired',
        revokedSuperseded: 'Your steering lease was superseded',
        revokedReleased: 'Steering released',
        revokedDetached: 'Steering ended — reconnect to continue',
        revokedEnded: 'Steering ended',
        reRequestHint: 'Request steering again to answer prompts',
        noPendingPrompts: 'No pending prompts',
        observeOnlyDestructive: 'This action can only be answered from the terminal',
        observeOnlyNoLease: 'Take steering to answer this prompt',
        permissionTitle: 'Permission request',
        approve: 'Approve',
        deny: 'Deny',
        elicitationTitle: 'Input requested',
        accept: 'Accept',
        decline: 'Decline',
        planTitle: 'Plan review',
        planApprove: 'Approve plan',
        planReject: 'Reject plan',
        planFeedbackPlaceholder: 'Optional feedback (why reject)',
        askUserTitle: 'Question',
        askUserPlaceholder: 'Type your answer…',
        send: 'Send',
        dismiss: 'Dismiss',
        sending: 'Sending…',
        outcomeApplied: 'Answer applied',
        outcomeDuplicate: 'Already sent',
        outcomeAlreadyResolved: 'Already resolved',
        outcomeOutOfScope: 'Not allowed for this session',
        outcomeDestructive: 'Blocked — terminal-only action',
        outcomeNoLease: 'You no longer hold steering',
        outcomeNotPending: 'This prompt is no longer pending',
        outcomeRateLimited: 'Too many answers — slow down',
        outcomeRateLimitedRetry: ({ seconds }: { seconds: number }) => `Too many answers — retry in ${seconds}s`,
        outcomeTransportFailed: 'Could not reach the terminal — try again',
        answeredHere: 'Answered from this device',
        answeredElsewhere: 'Answered at the terminal or another device',
    },

} as const;

export type Translations = typeof en;

type TranslationValue<T> = T extends string
    ? string
    : T extends (...args: any[]) => string
    ? T
    : T extends object
    ? { readonly [K in keyof T]: TranslationValue<T[K]> }
    : T;

/**
 * Generic translation type that matches the structure of Translations
 * but allows different string values (for other languages)
 */
export type TranslationStructure = TranslationValue<Translations>;
