export const HAPPY_FORKED_FROM_SESSION_ID = 'HAPPY_FORKED_FROM_SESSION_ID' as const;
export const HAPPY_PARENT_SESSION_ID = 'HAPPY_PARENT_SESSION_ID' as const;
export const HAPPY_CURRENT_SESSION_ID = 'HAPPY_CURRENT_SESSION_ID' as const;
export const HAPPY_DAEMON_CONTROL_URL = 'HAPPY_DAEMON_CONTROL_URL' as const;
